"""
PosterGeneration model for marketing poster metadata
Stores information about AI-generated marketing posters
"""

from typing import Optional, TYPE_CHECKING
from sqlmodel import Field, Relationship
from uuid import UUID
from app.models.base import UUIDModel

if TYPE_CHECKING:
    from app.models.tenant import Tenant


class PosterGeneration(UUIDModel, table=True):
    """
    Poster Generation model for storing marketing poster metadata.
    Generated by AI and uploaded to ImageKit CDN.
    Matches the MCP server's poster_generations table structure.
    """

    __tablename__ = "poster_generations"

    # Foreign key to tenant (multi-tenant isolation)
    tenant_id: UUID = Field(foreign_key="tenants.id", nullable=False, index=True)

    # ImageKit CDN URL for the generated poster
    image_url: str = Field(nullable=False)

    # Social media caption generated with the poster
    image_caption: Optional[str] = Field(default=None, nullable=True)

    # Relationships
    tenant: "Tenant" = Relationship(back_populates="poster_generations")
