"""add_poster_generations_table

Revision ID: 87229900a69d
Revises: fca1930d8a4d
Create Date: 2025-11-15 14:43:20.853131

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "87229900a69d"
down_revision: Union[str, Sequence[str], None] = "fca1930d8a4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "poster_generations",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("image_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("image_caption", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Single column index for basic tenant lookups
    op.create_index(
        op.f("ix_poster_generations_tenant_id"),
        "poster_generations",
        ["tenant_id"],
        unique=False,
    )

    # Composite index for optimized queries: tenant + created_at DESC (most common query pattern)
    op.create_index(
        "ix_poster_generations_tenant_created",
        "poster_generations",
        ["tenant_id", sa.text("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_poster_generations_tenant_id"), table_name="poster_generations"
    )
    op.drop_table("poster_generations")
    # ### end Alembic commands ###
