"""update_user_phone_primary_key_and_add_whatsapp_creds

Revision ID: 902506a98b4a
Revises: e7c282f29fad
Create Date: 2025-11-11 20:02:26.497341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "902506a98b4a"
down_revision: Union[str, Sequence[str], None] = "e7c282f29fad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Create whatsapp_creds table first (before changing users table)
    op.create_table(
        "whatsapp_creds",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("instance_name", sa.String(), nullable=False),
        sa.Column("qr_code", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instance_name"],
            ["users.phone_no"],
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_whatsapp_creds_instance_name"),
        "whatsapp_creds",
        ["instance_name"],
        unique=True,
    )
    op.create_index(
        op.f("ix_whatsapp_creds_tenant_id"),
        "whatsapp_creds",
        ["tenant_id"],
        unique=True,
    )

    # Step 2: Update user_messages table
    op.add_column("user_messages", sa.Column("phone_no", sa.String(), nullable=True))
    op.drop_index(op.f("ix_user_messages_author"), table_name="user_messages")
    op.create_index(
        "ix_user_messages_phone", "user_messages", ["phone_no"], unique=False
    )
    op.drop_constraint(
        op.f("user_messages_author_id_fkey"), "user_messages", type_="foreignkey"
    )
    op.create_foreign_key(None, "user_messages", "users", ["phone_no"], ["phone_no"])
    op.drop_column("user_messages", "status")
    op.drop_column("user_messages", "provider_meta")
    op.drop_column("user_messages", "tokens")
    op.drop_column("user_messages", "author_id")

    # Step 3: Update users table - change primary key from id to phone_no
    # Drop the old primary key constraint
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_pkey")
    # Add phone_no as primary key
    op.execute("ALTER TABLE users ADD PRIMARY KEY (phone_no)")
    # Drop the old UUID id column and other removed fields
    op.drop_column("users", "id")
    op.drop_column("users", "name")
    op.drop_column("users", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Restore users table structure
    op.add_column(
        "users",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("role", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # Change primary key back from phone_no to id
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_pkey")
    op.execute("ALTER TABLE users ADD PRIMARY KEY (id)")

    # Step 2: Restore user_messages table
    op.add_column(
        "user_messages",
        sa.Column("author_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "user_messages",
        sa.Column("tokens", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user_messages",
        sa.Column(
            "provider_meta",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "user_messages",
        sa.Column(
            "status",
            sa.VARCHAR(),
            server_default=sa.text("'completed'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # Drop the phone_no foreign key
    op.execute(
        "ALTER TABLE user_messages DROP CONSTRAINT IF EXISTS user_messages_phone_no_fkey"
    )
    op.create_foreign_key(
        op.f("user_messages_author_id_fkey"),
        "user_messages",
        "users",
        ["author_id"],
        ["id"],
    )
    op.drop_index("ix_user_messages_phone", table_name="user_messages")
    op.create_index(
        op.f("ix_user_messages_author"), "user_messages", ["author_id"], unique=False
    )
    op.drop_column("user_messages", "phone_no")

    # Step 3: Drop whatsapp_creds table
    op.drop_index(op.f("ix_whatsapp_creds_tenant_id"), table_name="whatsapp_creds")
    op.drop_index(op.f("ix_whatsapp_creds_instance_name"), table_name="whatsapp_creds")
    op.drop_table("whatsapp_creds")
    # ### end Alembic commands ###
