"""remove_author_id_from_messages

Revision ID: e7c282f29fad
Revises: google_sheets_v1
Create Date: 2025-11-11 19:05:44.739536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = "e7c282f29fad"
down_revision: Union[str, Sequence[str], None] = "google_sheets_v1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # CRITICAL: Drop foreign key from user_messages BEFORE dropping user_conversations table
    op.drop_constraint(
        op.f("user_messages_conversation_id_fkey"), "user_messages", type_="foreignkey"
    )

    op.drop_index(
        op.f("idx_user_conversations_created_at"), table_name="user_conversations"
    )
    op.drop_index(
        op.f("idx_user_conversations_user_id"), table_name="user_conversations"
    )
    op.drop_table("user_conversations")
    op.drop_index(op.f("idx_tenant_date"), table_name="poster_generations")
    op.drop_table("poster_generations")
    op.drop_index(op.f("idx_conversations_created_at"), table_name="conversations")
    op.drop_index(op.f("idx_conversations_tenant_id"), table_name="conversations")
    op.create_index(
        op.f("ix_conversations_tenant_id"), "conversations", ["tenant_id"], unique=False
    )
    op.drop_constraint(
        op.f("conversations_tenant_id_fkey"), "conversations", type_="foreignkey"
    )
    op.create_foreign_key(None, "conversations", "tenants", ["tenant_id"], ["id"])
    op.drop_column("conversations", "updated_at")
    op.alter_column(
        "google_sheets_connections",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("google_sheets_connections", "updated_at")
    op.alter_column(
        "messages",
        "content",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=True,
    )
    op.alter_column("messages", "tokens", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "messages",
        "provider_meta",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_messages_conversation_id"), table_name="messages")
    op.drop_index(op.f("idx_messages_created_at"), table_name="messages")
    op.drop_index(op.f("idx_messages_tenant_id"), table_name="messages")
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_messages_tenant", "messages", ["tenant_id"], unique=False)
    op.create_index(
        op.f("ix_messages_tenant_id"), "messages", ["tenant_id"], unique=False
    )
    op.drop_constraint(
        op.f("messages_conversation_id_fkey"), "messages", type_="foreignkey"
    )
    op.drop_constraint(op.f("messages_tenant_id_fkey"), "messages", type_="foreignkey")
    op.create_foreign_key(
        None, "messages", "conversations", ["conversation_id"], ["id"]
    )
    op.create_foreign_key(None, "messages", "tenants", ["tenant_id"], ["id"])
    op.drop_column("messages", "author_id")
    op.drop_column("messages", "updated_at")
    op.drop_index(op.f("idx_quickbooks_realm_id"), table_name="quickbooks_connections")
    op.drop_index(op.f("idx_quickbooks_tenant_id"), table_name="quickbooks_connections")
    op.create_index(
        op.f("ix_quickbooks_connections_realm_id"),
        "quickbooks_connections",
        ["realm_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quickbooks_connections_tenant_id"),
        "quickbooks_connections",
        ["tenant_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("quickbooks_connections_tenant_id_fkey"),
        "quickbooks_connections",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "quickbooks_connections", "tenants", ["tenant_id"], ["id"]
    )
    op.drop_column("quickbooks_connections", "updated_at")
    op.drop_index(op.f("idx_refresh_tokens_tenant_id"), table_name="refresh_tokens")
    op.create_index(
        op.f("ix_refresh_tokens_tenant_id"),
        "refresh_tokens",
        ["tenant_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("refresh_tokens_tenant_id_fkey"), "refresh_tokens", type_="foreignkey"
    )
    op.create_foreign_key(None, "refresh_tokens", "tenants", ["tenant_id"], ["id"])
    op.drop_index(op.f("idx_tenants_email"), table_name="tenants")
    op.drop_index(op.f("idx_tenants_oauth"), table_name="tenants")
    op.drop_index(op.f("idx_tenants_slug"), table_name="tenants")
    op.drop_constraint(op.f("tenants_email_key"), "tenants", type_="unique")
    op.drop_constraint(op.f("tenants_slug_key"), "tenants", type_="unique")
    op.create_index(op.f("ix_tenants_email"), "tenants", ["email"], unique=True)
    op.create_index(op.f("ix_tenants_oauth_id"), "tenants", ["oauth_id"], unique=False)
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=False)
    op.drop_column("tenants", "last_login_at")
    op.drop_column("tenants", "email_verified_at")
    op.drop_column("tenants", "updated_at")
    op.add_column("user_messages", sa.Column("tenant_id", sa.Uuid(), nullable=False))
    op.add_column("user_messages", sa.Column("author_id", sa.Uuid(), nullable=True))
    op.alter_column(
        "user_messages",
        "content",
        existing_type=sa.TEXT(),
        type_=sqlmodel.sql.sqltypes.AutoString(),
        nullable=True,
    )
    op.alter_column(
        "user_messages", "tokens", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "user_messages",
        "provider_meta",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
    )
    op.drop_index(op.f("idx_user_messages_conversation_id"), table_name="user_messages")
    op.drop_index(op.f("idx_user_messages_created_at"), table_name="user_messages")
    op.create_index(
        "ix_user_messages_author", "user_messages", ["author_id"], unique=False
    )
    op.create_index(
        "ix_user_messages_created", "user_messages", ["created_at"], unique=False
    )
    op.create_index(
        "ix_user_messages_tenant", "user_messages", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_messages_tenant_id"), "user_messages", ["tenant_id"], unique=False
    )
    # Foreign key already dropped at the beginning of migration
    op.create_foreign_key(None, "user_messages", "tenants", ["tenant_id"], ["id"])
    op.create_foreign_key(None, "user_messages", "users", ["author_id"], ["id"])
    op.drop_column("user_messages", "conversation_id")
    op.drop_index(op.f("idx_users_phone"), table_name="users")
    op.drop_index(op.f("idx_users_tenant_id"), table_name="users")
    op.drop_constraint(op.f("users_phone_no_key"), "users", type_="unique")
    op.create_index(op.f("ix_users_phone_no"), "users", ["phone_no"], unique=True)
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.drop_constraint(op.f("users_tenant_id_fkey"), "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "tenants", ["tenant_id"], ["id"])
    op.drop_column("users", "updated_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_tenant_id_fkey"),
        "users",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_index(op.f("ix_users_phone_no"), table_name="users")
    op.create_unique_constraint(
        op.f("users_phone_no_key"),
        "users",
        ["phone_no"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("idx_users_tenant_id"), "users", ["tenant_id"], unique=False)
    op.create_index(op.f("idx_users_phone"), "users", ["phone_no"], unique=True)
    op.add_column(
        "user_messages",
        sa.Column("conversation_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "user_messages", type_="foreignkey")
    op.drop_constraint(None, "user_messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("user_messages_conversation_id_fkey"),
        "user_messages",
        "user_conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_user_messages_tenant_id"), table_name="user_messages")
    op.drop_index("ix_user_messages_tenant", table_name="user_messages")
    op.drop_index("ix_user_messages_created", table_name="user_messages")
    op.drop_index("ix_user_messages_author", table_name="user_messages")
    op.create_index(
        op.f("idx_user_messages_created_at"),
        "user_messages",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("idx_user_messages_conversation_id"),
        "user_messages",
        ["conversation_id"],
        unique=False,
    )
    op.alter_column(
        "user_messages",
        "provider_meta",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column(
        "user_messages", "tokens", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "user_messages",
        "content",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        nullable=False,
    )
    op.drop_column("user_messages", "author_id")
    op.drop_column("user_messages", "tenant_id")
    op.add_column(
        "tenants",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "tenants",
        sa.Column(
            "email_verified_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tenants",
        sa.Column(
            "last_login_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_oauth_id"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_email"), table_name="tenants")
    op.create_unique_constraint(
        op.f("tenants_slug_key"),
        "tenants",
        ["slug"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("tenants_email_key"),
        "tenants",
        ["email"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("idx_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_index(
        op.f("idx_tenants_oauth"),
        "tenants",
        ["oauth_provider", "oauth_id"],
        unique=False,
    )
    op.create_index(op.f("idx_tenants_email"), "tenants", ["email"], unique=True)
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(
        op.f("refresh_tokens_tenant_id_fkey"),
        "refresh_tokens",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_refresh_tokens_tenant_id"), table_name="refresh_tokens")
    op.create_index(
        op.f("idx_refresh_tokens_tenant_id"),
        "refresh_tokens",
        ["tenant_id"],
        unique=False,
    )
    op.add_column(
        "quickbooks_connections",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "quickbooks_connections", type_="foreignkey")
    op.create_foreign_key(
        op.f("quickbooks_connections_tenant_id_fkey"),
        "quickbooks_connections",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(
        op.f("ix_quickbooks_connections_tenant_id"), table_name="quickbooks_connections"
    )
    op.drop_index(
        op.f("ix_quickbooks_connections_realm_id"), table_name="quickbooks_connections"
    )
    op.create_index(
        op.f("idx_quickbooks_tenant_id"),
        "quickbooks_connections",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_quickbooks_realm_id"),
        "quickbooks_connections",
        ["realm_id"],
        unique=False,
    )
    op.add_column(
        "messages",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "messages",
        sa.Column("author_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.create_foreign_key(
        op.f("messages_tenant_id_fkey"),
        "messages",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("messages_conversation_id_fkey"),
        "messages",
        "conversations",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_messages_tenant_id"), table_name="messages")
    op.drop_index("ix_messages_tenant", table_name="messages")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.create_index(
        op.f("idx_messages_tenant_id"), "messages", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("idx_messages_created_at"), "messages", ["created_at"], unique=False
    )
    op.create_index(
        op.f("idx_messages_conversation_id"),
        "messages",
        ["conversation_id"],
        unique=False,
    )
    op.alter_column(
        "messages",
        "provider_meta",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.alter_column("messages", "tokens", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "messages",
        "content",
        existing_type=sqlmodel.sql.sqltypes.AutoString(),
        type_=sa.TEXT(),
        nullable=False,
    )
    op.add_column(
        "google_sheets_connections",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "google_sheets_connections",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.add_column(
        "conversations",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "conversations", type_="foreignkey")
    op.create_foreign_key(
        op.f("conversations_tenant_id_fkey"),
        "conversations",
        "tenants",
        ["tenant_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_conversations_tenant_id"), table_name="conversations")
    op.create_index(
        op.f("idx_conversations_tenant_id"),
        "conversations",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_conversations_created_at"),
        "conversations",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "poster_generations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_date",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "tenant_id", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
        sa.Column("image_url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("image_caption", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("poster_generations_pkey")),
    )
    op.create_index(
        op.f("idx_tenant_date"),
        "poster_generations",
        ["tenant_id", sa.literal_column("created_date DESC")],
        unique=False,
    )
    op.create_table(
        "user_conversations",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("model", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("user_conversations_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_conversations_pkey")),
    )
    op.create_index(
        op.f("idx_user_conversations_user_id"),
        "user_conversations",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_user_conversations_created_at"),
        "user_conversations",
        ["created_at"],
        unique=False,
    )
    # ### end Alembic commands ###
