"""update whatsapp_creds add instance_name

Revision ID: fca1930d8a4d
Revises: 4ce138b63426
Create Date: 2025-11-14 20:30:24.957376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fca1930d8a4d'
down_revision: Union[str, Sequence[str], None] = '4ce138b63426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old foreign key constraint on instance_name
    op.drop_constraint(op.f('whatsapp_creds_instance_name_fkey'), 'whatsapp_creds', type_='foreignkey')
    
    # Convert instance_name from VARCHAR to UUID using tenant_id values
    op.execute('UPDATE whatsapp_creds SET instance_name = tenant_id::text')
    op.alter_column('whatsapp_creds', 'instance_name',
               existing_type=sa.VARCHAR(),
               type_=sa.Uuid(),
               existing_nullable=False,
               postgresql_using='instance_name::uuid')
    
    # Drop tenant_id column and its constraints
    op.drop_index(op.f('ix_whatsapp_creds_tenant_id'), table_name='whatsapp_creds')
    op.drop_constraint(op.f('whatsapp_creds_tenant_id_fkey'), 'whatsapp_creds', type_='foreignkey')
    op.drop_column('whatsapp_creds', 'tenant_id')
    
    # Create new foreign key from instance_name to tenants
    op.create_foreign_key(None, 'whatsapp_creds', 'tenants', ['instance_name'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whatsapp_creds', sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'whatsapp_creds', type_='foreignkey')
    op.create_foreign_key(op.f('whatsapp_creds_tenant_id_fkey'), 'whatsapp_creds', 'tenants', ['tenant_id'], ['id'])
    op.create_foreign_key(op.f('whatsapp_creds_instance_name_fkey'), 'whatsapp_creds', 'users', ['instance_name'], ['phone_no'])
    op.create_index(op.f('ix_whatsapp_creds_tenant_id'), 'whatsapp_creds', ['tenant_id'], unique=True)
    op.alter_column('whatsapp_creds', 'instance_name',
               existing_type=sa.Uuid(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
